version: '3.1'

services:
  local-portainer:
    image: portainer/portainer:1.12.4
    restart: "no"
    ports:
      - "$PORTAINER_9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  local-redis:
    image: redis:alpine
